/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaliRouteImport } from './routes/wali'
import { Route as UstadzRouteImport } from './routes/ustadz'
import { Route as SantriRouteImport } from './routes/santri'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaliIndexRouteImport } from './routes/wali/index'
import { Route as UstadzIndexRouteImport } from './routes/ustadz/index'
import { Route as SantriIndexRouteImport } from './routes/santri/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'

const WaliRoute = WaliRouteImport.update({
  id: '/wali',
  path: '/wali',
  getParentRoute: () => rootRouteImport,
} as any)
const UstadzRoute = UstadzRouteImport.update({
  id: '/ustadz',
  path: '/ustadz',
  getParentRoute: () => rootRouteImport,
} as any)
const SantriRoute = SantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaliIndexRoute = WaliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WaliRoute,
} as any)
const UstadzIndexRoute = UstadzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UstadzRoute,
} as any)
const SantriIndexRoute = SantriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SantriRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/santri': typeof SantriRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/santri': typeof SantriIndexRoute
  '/ustadz': typeof UstadzIndexRoute
  '/wali': typeof WaliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/santri': typeof SantriRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/santri'
    | '/ustadz'
    | '/wali'
    | '/admin/'
    | '/santri/'
    | '/ustadz/'
    | '/wali/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin' | '/santri' | '/ustadz' | '/wali'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/santri'
    | '/ustadz'
    | '/wali'
    | '/admin/'
    | '/santri/'
    | '/ustadz/'
    | '/wali/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SantriRoute: typeof SantriRouteWithChildren
  UstadzRoute: typeof UstadzRouteWithChildren
  WaliRoute: typeof WaliRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wali': {
      id: '/wali'
      path: '/wali'
      fullPath: '/wali'
      preLoaderRoute: typeof WaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustadz': {
      id: '/ustadz'
      path: '/ustadz'
      fullPath: '/ustadz'
      preLoaderRoute: typeof UstadzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santri': {
      id: '/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof SantriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wali/': {
      id: '/wali/'
      path: '/'
      fullPath: '/wali/'
      preLoaderRoute: typeof WaliIndexRouteImport
      parentRoute: typeof WaliRoute
    }
    '/ustadz/': {
      id: '/ustadz/'
      path: '/'
      fullPath: '/ustadz/'
      preLoaderRoute: typeof UstadzIndexRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/santri/': {
      id: '/santri/'
      path: '/'
      fullPath: '/santri/'
      preLoaderRoute: typeof SantriIndexRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SantriRouteChildren {
  SantriIndexRoute: typeof SantriIndexRoute
}

const SantriRouteChildren: SantriRouteChildren = {
  SantriIndexRoute: SantriIndexRoute,
}

const SantriRouteWithChildren =
  SantriRoute._addFileChildren(SantriRouteChildren)

interface UstadzRouteChildren {
  UstadzIndexRoute: typeof UstadzIndexRoute
}

const UstadzRouteChildren: UstadzRouteChildren = {
  UstadzIndexRoute: UstadzIndexRoute,
}

const UstadzRouteWithChildren =
  UstadzRoute._addFileChildren(UstadzRouteChildren)

interface WaliRouteChildren {
  WaliIndexRoute: typeof WaliIndexRoute
}

const WaliRouteChildren: WaliRouteChildren = {
  WaliIndexRoute: WaliIndexRoute,
}

const WaliRouteWithChildren = WaliRoute._addFileChildren(WaliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SantriRoute: SantriRouteWithChildren,
  UstadzRoute: UstadzRouteWithChildren,
  WaliRoute: WaliRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
