/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaliRouteImport } from './routes/wali'
import { Route as UstadzRouteImport } from './routes/ustadz'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SantriRouteImport } from './routes/santri'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WaliIndexRouteImport } from './routes/wali/index'
import { Route as UstadzIndexRouteImport } from './routes/ustadz/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SantriIndexRouteImport } from './routes/santri/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as WaliUjianRouteImport } from './routes/wali/ujian'
import { Route as WaliProfilRouteImport } from './routes/wali/profil'
import { Route as WaliJadwalRouteImport } from './routes/wali/jadwal'
import { Route as UstadzUjianRouteImport } from './routes/ustadz/ujian'
import { Route as UstadzRiwayatRouteImport } from './routes/ustadz/riwayat'
import { Route as UstadzProfilRouteImport } from './routes/ustadz/profil'
import { Route as UstadzPantauRouteImport } from './routes/ustadz/pantau'
import { Route as UstadzInputRouteImport } from './routes/ustadz/input'
import { Route as UstadzAbsensiRouteImport } from './routes/ustadz/absensi'
import { Route as SantriUjianRouteImport } from './routes/santri/ujian'
import { Route as SantriRiwayatRouteImport } from './routes/santri/riwayat'
import { Route as SantriProfilRouteImport } from './routes/santri/profil'
import { Route as SantriInputRouteImport } from './routes/santri/input'
import { Route as AdminUstadzRouteImport } from './routes/admin/ustadz'
import { Route as AdminUjianRouteImport } from './routes/admin/ujian'
import { Route as AdminSantriRouteImport } from './routes/admin/santri'
import { Route as AdminPengaturanRouteImport } from './routes/admin/pengaturan'
import { Route as AdminLaporanRouteImport } from './routes/admin/laporan'
import { Route as AdminKelasRouteImport } from './routes/admin/kelas'
import { Route as WaliTiketIndexRouteImport } from './routes/wali/tiket/index'
import { Route as UstadzTiketIndexRouteImport } from './routes/ustadz/tiket/index'
import { Route as SuperadminTiketIndexRouteImport } from './routes/superadmin/tiket/index'
import { Route as SuperadminLembagaIndexRouteImport } from './routes/superadmin/lembaga/index'
import { Route as SantriTiketIndexRouteImport } from './routes/santri/tiket/index'
import { Route as AdminTiketIndexRouteImport } from './routes/admin/tiket/index'
import { Route as AdminRaporIndexRouteImport } from './routes/admin/rapor/index'
import { Route as WaliTiketBuatRouteImport } from './routes/wali/tiket/buat'
import { Route as WaliTiketTiketIdRouteImport } from './routes/wali/tiket/$tiketId'
import { Route as UstadzTiketBuatRouteImport } from './routes/ustadz/tiket/buat'
import { Route as UstadzTiketTiketIdRouteImport } from './routes/ustadz/tiket/$tiketId'
import { Route as SuperadminTiketBuatRouteImport } from './routes/superadmin/tiket/buat'
import { Route as SuperadminTiketTiketIdRouteImport } from './routes/superadmin/tiket/$tiketId'
import { Route as SuperadminLembagaTenantIdRouteImport } from './routes/superadmin/lembaga/$tenantId'
import { Route as SantriTiketBuatRouteImport } from './routes/santri/tiket/buat'
import { Route as SantriTiketTiketIdRouteImport } from './routes/santri/tiket/$tiketId'
import { Route as AdminTiketBuatRouteImport } from './routes/admin/tiket/buat'
import { Route as AdminTiketTiketIdRouteImport } from './routes/admin/tiket/$tiketId'
import { Route as AdminRaporSantriIdRouteImport } from './routes/admin/rapor/$santriId'

const WaliRoute = WaliRouteImport.update({
  id: '/wali',
  path: '/wali',
  getParentRoute: () => rootRouteImport,
} as any)
const UstadzRoute = UstadzRouteImport.update({
  id: '/ustadz',
  path: '/ustadz',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SantriRoute = SantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WaliIndexRoute = WaliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WaliRoute,
} as any)
const UstadzIndexRoute = UstadzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UstadzRoute,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SantriIndexRoute = SantriIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SantriRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WaliUjianRoute = WaliUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => WaliRoute,
} as any)
const WaliProfilRoute = WaliProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => WaliRoute,
} as any)
const WaliJadwalRoute = WaliJadwalRouteImport.update({
  id: '/jadwal',
  path: '/jadwal',
  getParentRoute: () => WaliRoute,
} as any)
const UstadzUjianRoute = UstadzUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzRiwayatRoute = UstadzRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzProfilRoute = UstadzProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzPantauRoute = UstadzPantauRouteImport.update({
  id: '/pantau',
  path: '/pantau',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzInputRoute = UstadzInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzAbsensiRoute = UstadzAbsensiRouteImport.update({
  id: '/absensi',
  path: '/absensi',
  getParentRoute: () => UstadzRoute,
} as any)
const SantriUjianRoute = SantriUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => SantriRoute,
} as any)
const SantriRiwayatRoute = SantriRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => SantriRoute,
} as any)
const SantriProfilRoute = SantriProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => SantriRoute,
} as any)
const SantriInputRoute = SantriInputRouteImport.update({
  id: '/input',
  path: '/input',
  getParentRoute: () => SantriRoute,
} as any)
const AdminUstadzRoute = AdminUstadzRouteImport.update({
  id: '/ustadz',
  path: '/ustadz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUjianRoute = AdminUjianRouteImport.update({
  id: '/ujian',
  path: '/ujian',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSantriRoute = AdminSantriRouteImport.update({
  id: '/santri',
  path: '/santri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaporanRoute = AdminLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKelasRoute = AdminKelasRouteImport.update({
  id: '/kelas',
  path: '/kelas',
  getParentRoute: () => AdminRoute,
} as any)
const WaliTiketIndexRoute = WaliTiketIndexRouteImport.update({
  id: '/tiket/',
  path: '/tiket/',
  getParentRoute: () => WaliRoute,
} as any)
const UstadzTiketIndexRoute = UstadzTiketIndexRouteImport.update({
  id: '/tiket/',
  path: '/tiket/',
  getParentRoute: () => UstadzRoute,
} as any)
const SuperadminTiketIndexRoute = SuperadminTiketIndexRouteImport.update({
  id: '/tiket/',
  path: '/tiket/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLembagaIndexRoute = SuperadminLembagaIndexRouteImport.update({
  id: '/lembaga/',
  path: '/lembaga/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SantriTiketIndexRoute = SantriTiketIndexRouteImport.update({
  id: '/tiket/',
  path: '/tiket/',
  getParentRoute: () => SantriRoute,
} as any)
const AdminTiketIndexRoute = AdminTiketIndexRouteImport.update({
  id: '/tiket/',
  path: '/tiket/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRaporIndexRoute = AdminRaporIndexRouteImport.update({
  id: '/rapor/',
  path: '/rapor/',
  getParentRoute: () => AdminRoute,
} as any)
const WaliTiketBuatRoute = WaliTiketBuatRouteImport.update({
  id: '/tiket/buat',
  path: '/tiket/buat',
  getParentRoute: () => WaliRoute,
} as any)
const WaliTiketTiketIdRoute = WaliTiketTiketIdRouteImport.update({
  id: '/tiket/$tiketId',
  path: '/tiket/$tiketId',
  getParentRoute: () => WaliRoute,
} as any)
const UstadzTiketBuatRoute = UstadzTiketBuatRouteImport.update({
  id: '/tiket/buat',
  path: '/tiket/buat',
  getParentRoute: () => UstadzRoute,
} as any)
const UstadzTiketTiketIdRoute = UstadzTiketTiketIdRouteImport.update({
  id: '/tiket/$tiketId',
  path: '/tiket/$tiketId',
  getParentRoute: () => UstadzRoute,
} as any)
const SuperadminTiketBuatRoute = SuperadminTiketBuatRouteImport.update({
  id: '/tiket/buat',
  path: '/tiket/buat',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminTiketTiketIdRoute = SuperadminTiketTiketIdRouteImport.update({
  id: '/tiket/$tiketId',
  path: '/tiket/$tiketId',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminLembagaTenantIdRoute =
  SuperadminLembagaTenantIdRouteImport.update({
    id: '/lembaga/$tenantId',
    path: '/lembaga/$tenantId',
    getParentRoute: () => SuperadminRoute,
  } as any)
const SantriTiketBuatRoute = SantriTiketBuatRouteImport.update({
  id: '/tiket/buat',
  path: '/tiket/buat',
  getParentRoute: () => SantriRoute,
} as any)
const SantriTiketTiketIdRoute = SantriTiketTiketIdRouteImport.update({
  id: '/tiket/$tiketId',
  path: '/tiket/$tiketId',
  getParentRoute: () => SantriRoute,
} as any)
const AdminTiketBuatRoute = AdminTiketBuatRouteImport.update({
  id: '/tiket/buat',
  path: '/tiket/buat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTiketTiketIdRoute = AdminTiketTiketIdRouteImport.update({
  id: '/tiket/$tiketId',
  path: '/tiket/$tiketId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRaporSantriIdRoute = AdminRaporSantriIdRouteImport.update({
  id: '/rapor/$santriId',
  path: '/rapor/$santriId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/santri': typeof SantriRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ujian': typeof AdminUjianRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/santri/input': typeof SantriInputRoute
  '/santri/profil': typeof SantriProfilRoute
  '/santri/riwayat': typeof SantriRiwayatRoute
  '/santri/ujian': typeof SantriUjianRoute
  '/ustadz/absensi': typeof UstadzAbsensiRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/pantau': typeof UstadzPantauRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/wali/jadwal': typeof WaliJadwalRoute
  '/wali/profil': typeof WaliProfilRoute
  '/wali/ujian': typeof WaliUjianRoute
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
  '/admin/rapor/$santriId': typeof AdminRaporSantriIdRoute
  '/admin/tiket/$tiketId': typeof AdminTiketTiketIdRoute
  '/admin/tiket/buat': typeof AdminTiketBuatRoute
  '/santri/tiket/$tiketId': typeof SantriTiketTiketIdRoute
  '/santri/tiket/buat': typeof SantriTiketBuatRoute
  '/superadmin/lembaga/$tenantId': typeof SuperadminLembagaTenantIdRoute
  '/superadmin/tiket/$tiketId': typeof SuperadminTiketTiketIdRoute
  '/superadmin/tiket/buat': typeof SuperadminTiketBuatRoute
  '/ustadz/tiket/$tiketId': typeof UstadzTiketTiketIdRoute
  '/ustadz/tiket/buat': typeof UstadzTiketBuatRoute
  '/wali/tiket/$tiketId': typeof WaliTiketTiketIdRoute
  '/wali/tiket/buat': typeof WaliTiketBuatRoute
  '/admin/rapor/': typeof AdminRaporIndexRoute
  '/admin/tiket/': typeof AdminTiketIndexRoute
  '/santri/tiket/': typeof SantriTiketIndexRoute
  '/superadmin/lembaga/': typeof SuperadminLembagaIndexRoute
  '/superadmin/tiket/': typeof SuperadminTiketIndexRoute
  '/ustadz/tiket/': typeof UstadzTiketIndexRoute
  '/wali/tiket/': typeof WaliTiketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ujian': typeof AdminUjianRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/santri/input': typeof SantriInputRoute
  '/santri/profil': typeof SantriProfilRoute
  '/santri/riwayat': typeof SantriRiwayatRoute
  '/santri/ujian': typeof SantriUjianRoute
  '/ustadz/absensi': typeof UstadzAbsensiRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/pantau': typeof UstadzPantauRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/wali/jadwal': typeof WaliJadwalRoute
  '/wali/profil': typeof WaliProfilRoute
  '/wali/ujian': typeof WaliUjianRoute
  '/admin': typeof AdminIndexRoute
  '/santri': typeof SantriIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/ustadz': typeof UstadzIndexRoute
  '/wali': typeof WaliIndexRoute
  '/admin/rapor/$santriId': typeof AdminRaporSantriIdRoute
  '/admin/tiket/$tiketId': typeof AdminTiketTiketIdRoute
  '/admin/tiket/buat': typeof AdminTiketBuatRoute
  '/santri/tiket/$tiketId': typeof SantriTiketTiketIdRoute
  '/santri/tiket/buat': typeof SantriTiketBuatRoute
  '/superadmin/lembaga/$tenantId': typeof SuperadminLembagaTenantIdRoute
  '/superadmin/tiket/$tiketId': typeof SuperadminTiketTiketIdRoute
  '/superadmin/tiket/buat': typeof SuperadminTiketBuatRoute
  '/ustadz/tiket/$tiketId': typeof UstadzTiketTiketIdRoute
  '/ustadz/tiket/buat': typeof UstadzTiketBuatRoute
  '/wali/tiket/$tiketId': typeof WaliTiketTiketIdRoute
  '/wali/tiket/buat': typeof WaliTiketBuatRoute
  '/admin/rapor': typeof AdminRaporIndexRoute
  '/admin/tiket': typeof AdminTiketIndexRoute
  '/santri/tiket': typeof SantriTiketIndexRoute
  '/superadmin/lembaga': typeof SuperadminLembagaIndexRoute
  '/superadmin/tiket': typeof SuperadminTiketIndexRoute
  '/ustadz/tiket': typeof UstadzTiketIndexRoute
  '/wali/tiket': typeof WaliTiketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/santri': typeof SantriRouteWithChildren
  '/superadmin': typeof SuperadminRouteWithChildren
  '/ustadz': typeof UstadzRouteWithChildren
  '/wali': typeof WaliRouteWithChildren
  '/admin/kelas': typeof AdminKelasRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/santri': typeof AdminSantriRoute
  '/admin/ujian': typeof AdminUjianRoute
  '/admin/ustadz': typeof AdminUstadzRoute
  '/santri/input': typeof SantriInputRoute
  '/santri/profil': typeof SantriProfilRoute
  '/santri/riwayat': typeof SantriRiwayatRoute
  '/santri/ujian': typeof SantriUjianRoute
  '/ustadz/absensi': typeof UstadzAbsensiRoute
  '/ustadz/input': typeof UstadzInputRoute
  '/ustadz/pantau': typeof UstadzPantauRoute
  '/ustadz/profil': typeof UstadzProfilRoute
  '/ustadz/riwayat': typeof UstadzRiwayatRoute
  '/ustadz/ujian': typeof UstadzUjianRoute
  '/wali/jadwal': typeof WaliJadwalRoute
  '/wali/profil': typeof WaliProfilRoute
  '/wali/ujian': typeof WaliUjianRoute
  '/admin/': typeof AdminIndexRoute
  '/santri/': typeof SantriIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/ustadz/': typeof UstadzIndexRoute
  '/wali/': typeof WaliIndexRoute
  '/admin/rapor/$santriId': typeof AdminRaporSantriIdRoute
  '/admin/tiket/$tiketId': typeof AdminTiketTiketIdRoute
  '/admin/tiket/buat': typeof AdminTiketBuatRoute
  '/santri/tiket/$tiketId': typeof SantriTiketTiketIdRoute
  '/santri/tiket/buat': typeof SantriTiketBuatRoute
  '/superadmin/lembaga/$tenantId': typeof SuperadminLembagaTenantIdRoute
  '/superadmin/tiket/$tiketId': typeof SuperadminTiketTiketIdRoute
  '/superadmin/tiket/buat': typeof SuperadminTiketBuatRoute
  '/ustadz/tiket/$tiketId': typeof UstadzTiketTiketIdRoute
  '/ustadz/tiket/buat': typeof UstadzTiketBuatRoute
  '/wali/tiket/$tiketId': typeof WaliTiketTiketIdRoute
  '/wali/tiket/buat': typeof WaliTiketBuatRoute
  '/admin/rapor/': typeof AdminRaporIndexRoute
  '/admin/tiket/': typeof AdminTiketIndexRoute
  '/santri/tiket/': typeof SantriTiketIndexRoute
  '/superadmin/lembaga/': typeof SuperadminLembagaIndexRoute
  '/superadmin/tiket/': typeof SuperadminTiketIndexRoute
  '/ustadz/tiket/': typeof UstadzTiketIndexRoute
  '/wali/tiket/': typeof WaliTiketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/santri'
    | '/superadmin'
    | '/ustadz'
    | '/wali'
    | '/admin/kelas'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/santri'
    | '/admin/ujian'
    | '/admin/ustadz'
    | '/santri/input'
    | '/santri/profil'
    | '/santri/riwayat'
    | '/santri/ujian'
    | '/ustadz/absensi'
    | '/ustadz/input'
    | '/ustadz/pantau'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/wali/jadwal'
    | '/wali/profil'
    | '/wali/ujian'
    | '/admin/'
    | '/santri/'
    | '/superadmin/'
    | '/ustadz/'
    | '/wali/'
    | '/admin/rapor/$santriId'
    | '/admin/tiket/$tiketId'
    | '/admin/tiket/buat'
    | '/santri/tiket/$tiketId'
    | '/santri/tiket/buat'
    | '/superadmin/lembaga/$tenantId'
    | '/superadmin/tiket/$tiketId'
    | '/superadmin/tiket/buat'
    | '/ustadz/tiket/$tiketId'
    | '/ustadz/tiket/buat'
    | '/wali/tiket/$tiketId'
    | '/wali/tiket/buat'
    | '/admin/rapor/'
    | '/admin/tiket/'
    | '/santri/tiket/'
    | '/superadmin/lembaga/'
    | '/superadmin/tiket/'
    | '/ustadz/tiket/'
    | '/wali/tiket/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/kelas'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/santri'
    | '/admin/ujian'
    | '/admin/ustadz'
    | '/santri/input'
    | '/santri/profil'
    | '/santri/riwayat'
    | '/santri/ujian'
    | '/ustadz/absensi'
    | '/ustadz/input'
    | '/ustadz/pantau'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/wali/jadwal'
    | '/wali/profil'
    | '/wali/ujian'
    | '/admin'
    | '/santri'
    | '/superadmin'
    | '/ustadz'
    | '/wali'
    | '/admin/rapor/$santriId'
    | '/admin/tiket/$tiketId'
    | '/admin/tiket/buat'
    | '/santri/tiket/$tiketId'
    | '/santri/tiket/buat'
    | '/superadmin/lembaga/$tenantId'
    | '/superadmin/tiket/$tiketId'
    | '/superadmin/tiket/buat'
    | '/ustadz/tiket/$tiketId'
    | '/ustadz/tiket/buat'
    | '/wali/tiket/$tiketId'
    | '/wali/tiket/buat'
    | '/admin/rapor'
    | '/admin/tiket'
    | '/santri/tiket'
    | '/superadmin/lembaga'
    | '/superadmin/tiket'
    | '/ustadz/tiket'
    | '/wali/tiket'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/santri'
    | '/superadmin'
    | '/ustadz'
    | '/wali'
    | '/admin/kelas'
    | '/admin/laporan'
    | '/admin/pengaturan'
    | '/admin/santri'
    | '/admin/ujian'
    | '/admin/ustadz'
    | '/santri/input'
    | '/santri/profil'
    | '/santri/riwayat'
    | '/santri/ujian'
    | '/ustadz/absensi'
    | '/ustadz/input'
    | '/ustadz/pantau'
    | '/ustadz/profil'
    | '/ustadz/riwayat'
    | '/ustadz/ujian'
    | '/wali/jadwal'
    | '/wali/profil'
    | '/wali/ujian'
    | '/admin/'
    | '/santri/'
    | '/superadmin/'
    | '/ustadz/'
    | '/wali/'
    | '/admin/rapor/$santriId'
    | '/admin/tiket/$tiketId'
    | '/admin/tiket/buat'
    | '/santri/tiket/$tiketId'
    | '/santri/tiket/buat'
    | '/superadmin/lembaga/$tenantId'
    | '/superadmin/tiket/$tiketId'
    | '/superadmin/tiket/buat'
    | '/ustadz/tiket/$tiketId'
    | '/ustadz/tiket/buat'
    | '/wali/tiket/$tiketId'
    | '/wali/tiket/buat'
    | '/admin/rapor/'
    | '/admin/tiket/'
    | '/santri/tiket/'
    | '/superadmin/lembaga/'
    | '/superadmin/tiket/'
    | '/ustadz/tiket/'
    | '/wali/tiket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SantriRoute: typeof SantriRouteWithChildren
  SuperadminRoute: typeof SuperadminRouteWithChildren
  UstadzRoute: typeof UstadzRouteWithChildren
  WaliRoute: typeof WaliRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wali': {
      id: '/wali'
      path: '/wali'
      fullPath: '/wali'
      preLoaderRoute: typeof WaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustadz': {
      id: '/ustadz'
      path: '/ustadz'
      fullPath: '/ustadz'
      preLoaderRoute: typeof UstadzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/santri': {
      id: '/santri'
      path: '/santri'
      fullPath: '/santri'
      preLoaderRoute: typeof SantriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wali/': {
      id: '/wali/'
      path: '/'
      fullPath: '/wali/'
      preLoaderRoute: typeof WaliIndexRouteImport
      parentRoute: typeof WaliRoute
    }
    '/ustadz/': {
      id: '/ustadz/'
      path: '/'
      fullPath: '/ustadz/'
      preLoaderRoute: typeof UstadzIndexRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/santri/': {
      id: '/santri/'
      path: '/'
      fullPath: '/santri/'
      preLoaderRoute: typeof SantriIndexRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wali/ujian': {
      id: '/wali/ujian'
      path: '/ujian'
      fullPath: '/wali/ujian'
      preLoaderRoute: typeof WaliUjianRouteImport
      parentRoute: typeof WaliRoute
    }
    '/wali/profil': {
      id: '/wali/profil'
      path: '/profil'
      fullPath: '/wali/profil'
      preLoaderRoute: typeof WaliProfilRouteImport
      parentRoute: typeof WaliRoute
    }
    '/wali/jadwal': {
      id: '/wali/jadwal'
      path: '/jadwal'
      fullPath: '/wali/jadwal'
      preLoaderRoute: typeof WaliJadwalRouteImport
      parentRoute: typeof WaliRoute
    }
    '/ustadz/ujian': {
      id: '/ustadz/ujian'
      path: '/ujian'
      fullPath: '/ustadz/ujian'
      preLoaderRoute: typeof UstadzUjianRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/riwayat': {
      id: '/ustadz/riwayat'
      path: '/riwayat'
      fullPath: '/ustadz/riwayat'
      preLoaderRoute: typeof UstadzRiwayatRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/profil': {
      id: '/ustadz/profil'
      path: '/profil'
      fullPath: '/ustadz/profil'
      preLoaderRoute: typeof UstadzProfilRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/pantau': {
      id: '/ustadz/pantau'
      path: '/pantau'
      fullPath: '/ustadz/pantau'
      preLoaderRoute: typeof UstadzPantauRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/input': {
      id: '/ustadz/input'
      path: '/input'
      fullPath: '/ustadz/input'
      preLoaderRoute: typeof UstadzInputRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/absensi': {
      id: '/ustadz/absensi'
      path: '/absensi'
      fullPath: '/ustadz/absensi'
      preLoaderRoute: typeof UstadzAbsensiRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/santri/ujian': {
      id: '/santri/ujian'
      path: '/ujian'
      fullPath: '/santri/ujian'
      preLoaderRoute: typeof SantriUjianRouteImport
      parentRoute: typeof SantriRoute
    }
    '/santri/riwayat': {
      id: '/santri/riwayat'
      path: '/riwayat'
      fullPath: '/santri/riwayat'
      preLoaderRoute: typeof SantriRiwayatRouteImport
      parentRoute: typeof SantriRoute
    }
    '/santri/profil': {
      id: '/santri/profil'
      path: '/profil'
      fullPath: '/santri/profil'
      preLoaderRoute: typeof SantriProfilRouteImport
      parentRoute: typeof SantriRoute
    }
    '/santri/input': {
      id: '/santri/input'
      path: '/input'
      fullPath: '/santri/input'
      preLoaderRoute: typeof SantriInputRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/ustadz': {
      id: '/admin/ustadz'
      path: '/ustadz'
      fullPath: '/admin/ustadz'
      preLoaderRoute: typeof AdminUstadzRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ujian': {
      id: '/admin/ujian'
      path: '/ujian'
      fullPath: '/admin/ujian'
      preLoaderRoute: typeof AdminUjianRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/santri': {
      id: '/admin/santri'
      path: '/santri'
      fullPath: '/admin/santri'
      preLoaderRoute: typeof AdminSantriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laporan': {
      id: '/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AdminLaporanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kelas': {
      id: '/admin/kelas'
      path: '/kelas'
      fullPath: '/admin/kelas'
      preLoaderRoute: typeof AdminKelasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wali/tiket/': {
      id: '/wali/tiket/'
      path: '/tiket'
      fullPath: '/wali/tiket/'
      preLoaderRoute: typeof WaliTiketIndexRouteImport
      parentRoute: typeof WaliRoute
    }
    '/ustadz/tiket/': {
      id: '/ustadz/tiket/'
      path: '/tiket'
      fullPath: '/ustadz/tiket/'
      preLoaderRoute: typeof UstadzTiketIndexRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/superadmin/tiket/': {
      id: '/superadmin/tiket/'
      path: '/tiket'
      fullPath: '/superadmin/tiket/'
      preLoaderRoute: typeof SuperadminTiketIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/lembaga/': {
      id: '/superadmin/lembaga/'
      path: '/lembaga'
      fullPath: '/superadmin/lembaga/'
      preLoaderRoute: typeof SuperadminLembagaIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/santri/tiket/': {
      id: '/santri/tiket/'
      path: '/tiket'
      fullPath: '/santri/tiket/'
      preLoaderRoute: typeof SantriTiketIndexRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/tiket/': {
      id: '/admin/tiket/'
      path: '/tiket'
      fullPath: '/admin/tiket/'
      preLoaderRoute: typeof AdminTiketIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rapor/': {
      id: '/admin/rapor/'
      path: '/rapor'
      fullPath: '/admin/rapor/'
      preLoaderRoute: typeof AdminRaporIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/wali/tiket/buat': {
      id: '/wali/tiket/buat'
      path: '/tiket/buat'
      fullPath: '/wali/tiket/buat'
      preLoaderRoute: typeof WaliTiketBuatRouteImport
      parentRoute: typeof WaliRoute
    }
    '/wali/tiket/$tiketId': {
      id: '/wali/tiket/$tiketId'
      path: '/tiket/$tiketId'
      fullPath: '/wali/tiket/$tiketId'
      preLoaderRoute: typeof WaliTiketTiketIdRouteImport
      parentRoute: typeof WaliRoute
    }
    '/ustadz/tiket/buat': {
      id: '/ustadz/tiket/buat'
      path: '/tiket/buat'
      fullPath: '/ustadz/tiket/buat'
      preLoaderRoute: typeof UstadzTiketBuatRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/ustadz/tiket/$tiketId': {
      id: '/ustadz/tiket/$tiketId'
      path: '/tiket/$tiketId'
      fullPath: '/ustadz/tiket/$tiketId'
      preLoaderRoute: typeof UstadzTiketTiketIdRouteImport
      parentRoute: typeof UstadzRoute
    }
    '/superadmin/tiket/buat': {
      id: '/superadmin/tiket/buat'
      path: '/tiket/buat'
      fullPath: '/superadmin/tiket/buat'
      preLoaderRoute: typeof SuperadminTiketBuatRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/tiket/$tiketId': {
      id: '/superadmin/tiket/$tiketId'
      path: '/tiket/$tiketId'
      fullPath: '/superadmin/tiket/$tiketId'
      preLoaderRoute: typeof SuperadminTiketTiketIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/lembaga/$tenantId': {
      id: '/superadmin/lembaga/$tenantId'
      path: '/lembaga/$tenantId'
      fullPath: '/superadmin/lembaga/$tenantId'
      preLoaderRoute: typeof SuperadminLembagaTenantIdRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/santri/tiket/buat': {
      id: '/santri/tiket/buat'
      path: '/tiket/buat'
      fullPath: '/santri/tiket/buat'
      preLoaderRoute: typeof SantriTiketBuatRouteImport
      parentRoute: typeof SantriRoute
    }
    '/santri/tiket/$tiketId': {
      id: '/santri/tiket/$tiketId'
      path: '/tiket/$tiketId'
      fullPath: '/santri/tiket/$tiketId'
      preLoaderRoute: typeof SantriTiketTiketIdRouteImport
      parentRoute: typeof SantriRoute
    }
    '/admin/tiket/buat': {
      id: '/admin/tiket/buat'
      path: '/tiket/buat'
      fullPath: '/admin/tiket/buat'
      preLoaderRoute: typeof AdminTiketBuatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tiket/$tiketId': {
      id: '/admin/tiket/$tiketId'
      path: '/tiket/$tiketId'
      fullPath: '/admin/tiket/$tiketId'
      preLoaderRoute: typeof AdminTiketTiketIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rapor/$santriId': {
      id: '/admin/rapor/$santriId'
      path: '/rapor/$santriId'
      fullPath: '/admin/rapor/$santriId'
      preLoaderRoute: typeof AdminRaporSantriIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKelasRoute: typeof AdminKelasRoute
  AdminLaporanRoute: typeof AdminLaporanRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminSantriRoute: typeof AdminSantriRoute
  AdminUjianRoute: typeof AdminUjianRoute
  AdminUstadzRoute: typeof AdminUstadzRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRaporSantriIdRoute: typeof AdminRaporSantriIdRoute
  AdminTiketTiketIdRoute: typeof AdminTiketTiketIdRoute
  AdminTiketBuatRoute: typeof AdminTiketBuatRoute
  AdminRaporIndexRoute: typeof AdminRaporIndexRoute
  AdminTiketIndexRoute: typeof AdminTiketIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKelasRoute: AdminKelasRoute,
  AdminLaporanRoute: AdminLaporanRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminSantriRoute: AdminSantriRoute,
  AdminUjianRoute: AdminUjianRoute,
  AdminUstadzRoute: AdminUstadzRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRaporSantriIdRoute: AdminRaporSantriIdRoute,
  AdminTiketTiketIdRoute: AdminTiketTiketIdRoute,
  AdminTiketBuatRoute: AdminTiketBuatRoute,
  AdminRaporIndexRoute: AdminRaporIndexRoute,
  AdminTiketIndexRoute: AdminTiketIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SantriRouteChildren {
  SantriInputRoute: typeof SantriInputRoute
  SantriProfilRoute: typeof SantriProfilRoute
  SantriRiwayatRoute: typeof SantriRiwayatRoute
  SantriUjianRoute: typeof SantriUjianRoute
  SantriIndexRoute: typeof SantriIndexRoute
  SantriTiketTiketIdRoute: typeof SantriTiketTiketIdRoute
  SantriTiketBuatRoute: typeof SantriTiketBuatRoute
  SantriTiketIndexRoute: typeof SantriTiketIndexRoute
}

const SantriRouteChildren: SantriRouteChildren = {
  SantriInputRoute: SantriInputRoute,
  SantriProfilRoute: SantriProfilRoute,
  SantriRiwayatRoute: SantriRiwayatRoute,
  SantriUjianRoute: SantriUjianRoute,
  SantriIndexRoute: SantriIndexRoute,
  SantriTiketTiketIdRoute: SantriTiketTiketIdRoute,
  SantriTiketBuatRoute: SantriTiketBuatRoute,
  SantriTiketIndexRoute: SantriTiketIndexRoute,
}

const SantriRouteWithChildren =
  SantriRoute._addFileChildren(SantriRouteChildren)

interface SuperadminRouteChildren {
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  SuperadminLembagaTenantIdRoute: typeof SuperadminLembagaTenantIdRoute
  SuperadminTiketTiketIdRoute: typeof SuperadminTiketTiketIdRoute
  SuperadminTiketBuatRoute: typeof SuperadminTiketBuatRoute
  SuperadminLembagaIndexRoute: typeof SuperadminLembagaIndexRoute
  SuperadminTiketIndexRoute: typeof SuperadminTiketIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminIndexRoute: SuperadminIndexRoute,
  SuperadminLembagaTenantIdRoute: SuperadminLembagaTenantIdRoute,
  SuperadminTiketTiketIdRoute: SuperadminTiketTiketIdRoute,
  SuperadminTiketBuatRoute: SuperadminTiketBuatRoute,
  SuperadminLembagaIndexRoute: SuperadminLembagaIndexRoute,
  SuperadminTiketIndexRoute: SuperadminTiketIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

interface UstadzRouteChildren {
  UstadzAbsensiRoute: typeof UstadzAbsensiRoute
  UstadzInputRoute: typeof UstadzInputRoute
  UstadzPantauRoute: typeof UstadzPantauRoute
  UstadzProfilRoute: typeof UstadzProfilRoute
  UstadzRiwayatRoute: typeof UstadzRiwayatRoute
  UstadzUjianRoute: typeof UstadzUjianRoute
  UstadzIndexRoute: typeof UstadzIndexRoute
  UstadzTiketTiketIdRoute: typeof UstadzTiketTiketIdRoute
  UstadzTiketBuatRoute: typeof UstadzTiketBuatRoute
  UstadzTiketIndexRoute: typeof UstadzTiketIndexRoute
}

const UstadzRouteChildren: UstadzRouteChildren = {
  UstadzAbsensiRoute: UstadzAbsensiRoute,
  UstadzInputRoute: UstadzInputRoute,
  UstadzPantauRoute: UstadzPantauRoute,
  UstadzProfilRoute: UstadzProfilRoute,
  UstadzRiwayatRoute: UstadzRiwayatRoute,
  UstadzUjianRoute: UstadzUjianRoute,
  UstadzIndexRoute: UstadzIndexRoute,
  UstadzTiketTiketIdRoute: UstadzTiketTiketIdRoute,
  UstadzTiketBuatRoute: UstadzTiketBuatRoute,
  UstadzTiketIndexRoute: UstadzTiketIndexRoute,
}

const UstadzRouteWithChildren =
  UstadzRoute._addFileChildren(UstadzRouteChildren)

interface WaliRouteChildren {
  WaliJadwalRoute: typeof WaliJadwalRoute
  WaliProfilRoute: typeof WaliProfilRoute
  WaliUjianRoute: typeof WaliUjianRoute
  WaliIndexRoute: typeof WaliIndexRoute
  WaliTiketTiketIdRoute: typeof WaliTiketTiketIdRoute
  WaliTiketBuatRoute: typeof WaliTiketBuatRoute
  WaliTiketIndexRoute: typeof WaliTiketIndexRoute
}

const WaliRouteChildren: WaliRouteChildren = {
  WaliJadwalRoute: WaliJadwalRoute,
  WaliProfilRoute: WaliProfilRoute,
  WaliUjianRoute: WaliUjianRoute,
  WaliIndexRoute: WaliIndexRoute,
  WaliTiketTiketIdRoute: WaliTiketTiketIdRoute,
  WaliTiketBuatRoute: WaliTiketBuatRoute,
  WaliTiketIndexRoute: WaliTiketIndexRoute,
}

const WaliRouteWithChildren = WaliRoute._addFileChildren(WaliRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SantriRoute: SantriRouteWithChildren,
  SuperadminRoute: SuperadminRouteWithChildren,
  UstadzRoute: UstadzRouteWithChildren,
  WaliRoute: WaliRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
